
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import env from "./src/core/env/env.js";
import "dotenv/config";
import { defineConfig} from "prisma/config";

export default defineConfig(
  {
  schema: "./src/core/database/prisma/models/schema.prisma",
  migrations: {
    path: "./src/core/database/prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env.DATABASE_URL!,
    directUrl: env.DIRECT_URL ?? env.DATABASE_URL!,
  },
});
